-- Tabla de Usuarios (Clientes)
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_BICI INT DEFAULT NULL,  -- Un usuario puede tener una bici asignada
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DNI VARCHAR(10) NOT NULL UNIQUE,
    TELEFONO VARCHAR(15) NOT NULL UNIQUE,
    DIRECCION TEXT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

-- Tabla de Bicicletas
CREATE TABLE BICICLETA (
    ID_BICI INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT DEFAULT NULL,
    ESTADO ENUM('disponible', 'en uso', 'averiada') NOT NULL DEFAULT 'disponible',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL
);

-- Tabla de Administradores
CREATE TABLE ADMINISTRATIVO (
    ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DIRECCION TEXT NOT NULL,
    DNI VARCHAR(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

-- Tabla de Incidencias
CREATE TABLE INCIDENCIA (
    ID_INC INT AUTO_INCREMENT PRIMARY KEY,
    ID_BICI INT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_BICI) REFERENCES BICICLETA(ID_BICI) ON DELETE CASCADE
);

-- Insertar un administrador por defecto
INSERT INTO ADMINISTRATIVO (NOMBRE, APELLIDO, DIRECCION, DNI, EMAIL, PASSWORD) 
VALUES ('Admin', 'Principal', 'Oficina Central', '12345678X', 'admin@busbici.com', '$2y$10$ejemploHashAqui...');

-- Tabla de Alquiler
CREATE TABLE ALQUILER (
    ID_ALQUILER INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_BICI INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA_RECOGIDA TIME NOT NULL,
    HORA_DEVOLUCION TIME NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_BICI) REFERENCES BICICLETA(ID_BICI)
);